// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aovmepkdnofcoltrquzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvdm1lcGtkbm9mY29sdHJxdXp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNjc0OTQsImV4cCI6MjA2MTk0MzQ5NH0.zLWIOMjp5qXJmL4Rje5WYc_057Rzw2qIVWmoobwfjtk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);